version: "3"
tasks:
  init:
    desc: "Initialize the Weather frontend"
    cmds:
      - echo "Initializing the Weather frontend..."
      - pnpm install

  start:
    desc: "Starts the rspack dev server"
    dir: ./
    cmds:
      - echo "Starting dev environment..."
      - pnpm run start:dev